version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: easy
      MYSQL_DATABASE: stock_data
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql-scripts/:/docker-entrypoint-initdb.d/
  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
volumes:
  db_data:
